server:
  port: 8080
  ssl:
    key-store-type: PKCS12
    key-store: /etc/evelyn/profile-service-keystore.p12
    key-store-password: changeit
    key-alias: 1
    trust-store: /etc/evelyn/truststore.p12
    trust-store-password: changeit

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    virtual-host: evelyn_vhost
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.evelyn.internal/auth/realms/evelyn-services-realm

org:
  evelyn:
    tlsEnabled: true
    profile:
      mongo-connection-string: ${MONGO_CONNECTION_URI}
      email-input-queue-name: send-mail

logging:
  level:
    root: DEBUG
