server:
  port: 8080
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}

org:
  evelyn:
    profile:
      mongo-connection-string: ${MONGO_CONNECTION_URI}
      email-input-queue-name: send-mail

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_URL}
  realm: evelyn-services-realm
  public-client: true
  resource: evelyn-ui
  principal-attribute: preferred_username
