server:
  port: 8081
spring:
  rabbitmq:
    port: 9082

org:
  evelyn:
    etcd-url: http://localhost:2379
    profile:
      mongo-connection-string: mongodb://localhost:9081
      email-input-queue-name: send-mail

keycloak:
  auth-server-url: http://localhost:9083/auth
  realm: evelyn-services-realm
  public-client: true
  resource: evelyn-ui
  principal-attribute: preferred_username

logging:
  level:
    org:
      springframework:
        security: DEBUG
