spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}

org:
  evelyn:
    email:
      email-input-queue-name: send-mail
      mail:
        host: ${MAIL_HOST}
        port: ${MAIL_PORT}
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
          mail.transport.protocol: smtp
          mail.smtp.host: ${MAIL_SMTP_HOST}
          mail.smtp.auth: true
          mail.smtp.starttls.enable: true
