apiVersion: apps/v1
kind: Deployment
metadata:
  name: evelyn-profile-service
  namespace: evelyn-services
  labels:
    app: evelyn-profile-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evelyn-profile-service
  template:
    metadata:
      labels:
        app: evelyn-profile-service
    spec:
      containers:
        - name: evelyn-profile-service
          imagePullPolicy: Always
          image: docker.pkg.github.com/ephyrasoftware/evelyn-service/evelyn-profile-service:dev
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: RABBITMQ_HOST
              value: "rabbitmq.evelyn-platform"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: MONGO_CONNECTION_URI
              value: mongodb://mongodb.evelyn-platform/
            - name: KEYCLOAK_AUTH_URL
              value: http://keycloak.evelyn-platform:8080/auth
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ghregcred
---
apiVersion: v1
kind: Service
metadata:
  name: evelyn-profile-service
spec:
  selector:
    app: evelyn-profile-service
  clusterIP: None
---
