server:
  port: 8080
  ssl:
    key-store-type: PKCS12
    key-store: /etc/evelyn/todo-service-keystore.p12
    key-store-password: changeit
    key-alias: 1
    trust-store: /etc/evelyn/truststore.p12
    trust-store-password: changeit

org:
  evelyn:
    tlsEnabled: true
    todo:
      mongo-connection-string: ${MONGO_CONNECTION_URI}

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_URL}
  realm: evelyn-services-realm
  public-client: true
  resource: evelyn-ui
  principal-attribute: sub
