server:
  port: 8080
  ssl:
    key-store-type: PKCS12
    key-store: /etc/evelyn/todo-service-keystore.p12
    key-store-password: changeit
    key-alias: 1
    trust-store: /etc/evelyn/truststore.p12
    trust-store-password: changeit

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.evelyn.internal/auth/realms/evelyn-services-realm

org:
  evelyn:
    tlsEnabled: true
    todo:
      mongo-connection-string: ${MONGO_CONNECTION_URI}
