server:
  port: 8083

org:
  evelyn:
    tlsEnabled: false
    etcd-url: http://localhost:2379
    task:
      mongo-connection-string: mongodb://localhost:9081

keycloak:
  auth-server-url: http://localhost:9083/auth
  realm: evelyn-services-realm
  public-client: true
  resource: evelyn-ui
  principal-attribute: preferred_username
