zuul:
  routes:
    profile:
      path: /profiles/**
      url: https://${PROFILE_SERVICE_HOST}/profiles
      sensitiveHeaders: Cookie,Set-Cookie
    group:
      path: /groups/**
      url: https://${GROUP_SERVICE_HOST}/groups
      sensitiveHeaders: Cookie,Set-Cookie
    task:
      path: /tasks/**
      url: https://${TASK_SERVICE_HOST}/tasks
      sensitiveHeaders: Cookie,Set-Cookie
    calendar:
      path: /calendars/**
      url: https://${CALENDAR_SERVICE_HOST}/calendars
      sensitiveHeaders: Cookie,Set-Cookie

server:
  port: 5000
  http2:
    enabled: true

  ssl:
    key-store-type: PKCS12
    key-store: /etc/evelyn/web-entry-point-keystore.p12
    key-store-password: changeit
    key-alias: 1
    trust-store: /etc/evelyn/truststore.p12
    trust-store-password: changeit

ribbon:
  IsSecure: true
  TrustStore: /etc/evelyn/truststore.p12
  TrustStorePassword: changeit
