zuul:
  routes:
    profile:
      path: /profiles/**
      url: http://${PROFILE_SERVICE_HOST}/profiles
    group:
      path: /groups/**
      url: http://${GROUP_SERVICE_HOST}/groups

server:
  port: 5000
