zuul:
  routes:
    profile:
      path: /profiles/**
      url: http://localhost:8081/profiles
    group:
      path: /groups/**
      url: http://localhost:8082/groups
    task:
      path: /tasks/**
      url: http://localhost:8083/tasks

server:
  port: 5000