spring:
  rabbitmq:
    port: 9082
    virtual-host: evelyn_vhost
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
      enabled: true
      location: ${java.io.tmpdir}

org:
  evelyn:
    tlsEnabled: false
    email:
      email-input-queue-name: send-mail
      mail:
        host: localhost
        port: 3025
        username: evelynmailer
        password: passwd
        properties:
          mail.transport.protocol: smtp
          mail.smtp.host: localhost
          mail.smtp.auth: true
          mail.smtp.starttls.enable: true
          mail.debug: true
    group:
      mongo-connection-string: mongodb://localhost:9081
      profile-service-url: http://localhost:8080
    profile:
      mongo-connection-string: mongodb://localhost:9081
      email-input-queue-name: send-mail
    task:
      mongo-connection-string: mongodb://localhost:9081
      profile-service-url: http://localhost:8080
    calendar:
      mongo-connection-string: mongodb://localhost:9081
      profile-service-url: http://localhost:8080

keycloak:
  auth-server-url: http://localhost:9083/auth
  realm: evelyn-services-realm
  public-client: true
  resource: evelyn-ui
  principal-attribute: sub
