server:
  port: 8082

keycloak:
  auth-server-url: http://localhost:9083/auth
  realm: evelyn-services-realm
  public-client: true
  resource: evelyn-ui
  principal-attribute: preferred_username

org:
  evelyn:
    group:
      mongo-connection-string: mongodb://localhost:9081
      profile-service-url: http://localhost:8081
