keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_URL}
  realm: evelyn-services-realm
  public-client: true
  resource: evelyn-ui
  principal-attribute: preferred_username

org:
  evelyn:
    group:
      mongo-connection-string: ${MONGO_CONNECTION_URI}
      profile-service-url: ${PROFILE_SERVICE_BASE_URL}
