server:
  port: 8080
  ssl:
    key-store-type: PKCS12
    key-store: /etc/evelyn/calendar-service-keystore.p12
    key-store-password: changeit
    key-alias: 1
    trust-store: /etc/evelyn/truststore.p12
    trust-store-password: changeit

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    virtual-host: evelyn_vhost
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
      enabled: true
      location: ${java.io.tmpdir}

org:
  evelyn:
    tlsEnabled: true
    calendar:
      mongo-connection-string: ${MONGO_CONNECTION_URI}
      profile-service-url: ${PROFILE_SERVICE_BASE_URL}

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_URL}
  realm: evelyn-services-realm
  public-client: true
  resource: evelyn-ui
  principal-attribute: sub
