server:
  port: 8084
spring:
  rabbitmq:
    port: 9082
    virtual-host: evelyn_vhost
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
      enabled: true
      location: ${java.io.tmpdir}

org:
  evelyn:
    tlsEnabled: false
    etcd-url: http://localhost:2379
    calendar:
      mongo-connection-string: mongodb://localhost:9081
      profile-service-url: http://localhost:8080

keycloak:
  auth-server-url: http://localhost:9083/auth
  realm: evelyn-services-realm
  public-client: true
  resource: evelyn-ui
  principal-attribute: preferred_username
