server:
  port: 8085

keycloak:
  auth-server-url: http://localhost:9083/auth
  realm: evelyn-services-realm
  public-client: true
  resource: evelyn-ui
  principal-attribute: preferred_username

logging:
  level:
    org:
      springframework:
        security: DEBUG

#keycloak-client:
#  server-url: http://localhost:9083/auth
#  realm: evelyn-services-realm
#
#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          evelyn-services-realm: # This is the id used inside the redirect-uri-template, must be the same as your realm
#            client-id: evelyn-services-auth
#            client-secret: a0fe1b28-02f1-4751-a4eb-a72f78882a47
#            client-name: some client
#            provider: keycloak
#            scope: openid, profile
#            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
#            authorization-grant-type: authorization_code
#        provider:
#          keycloak:
#            token-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/token
#            authorization-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/auth
#            user-info-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/userinfo
#            jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
#            user-name-attribute: preferred_username
